package com.crx.quanxian.model;

import java.util.List;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rname
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    private String rname;
    
    private  List<Res> resources;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rid
     *
     * @return the value of role.rid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rid
     *
     * @param rid the value for role.rid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rname
     *
     * @return the value of role.rname
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rname
     *
     * @param rname the value for role.rname
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

	public List<Res> getResources() {
		return resources;
	}

	public void setResources(List<Res> resources) {
		this.resources = resources;
	}
    
}