package com.crx.quanxian.model;

public class RoleResKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res.rid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res.resid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    private Integer resid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res.rid
     *
     * @return the value of role_res.rid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res.rid
     *
     * @param rid the value for role_res.rid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res.resid
     *
     * @return the value of role_res.resid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res.resid
     *
     * @param resid the value for role_res.resid
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }
}