package com.crx.quanxian.dao;

import com.crx.quanxian.model.Res;
import com.crx.quanxian.model.ResExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    long countByExample(ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int deleteByExample(ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int deleteByPrimaryKey(Integer resid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int insert(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int insertSelective(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    List<Res> selectByExample(ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    Res selectByPrimaryKey(Integer resid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Res record, @Param("example") ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int updateByExample(@Param("record") Res record, @Param("example") ResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int updateByPrimaryKeySelective(Res record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res
     *
     * @mbg.generated Wed Dec 23 15:48:24 CST 2020
     */
    int updateByPrimaryKey(Res record);
}